// Rewrite the instructions in your own words: we want to make a program that generates capitalized acronym for some English phrases.

// Write the objectives and the tests: the objectives: develop a generator of acronym for any given phrase.

// Write the pseudocode: 
   /* - prompt the user with a message to insert his/her phrase.
      - take the first letter of each word in the phrase.
      - use the space delimiter to differ between the words in the phrase.
      - repeat the same process for all the words in the phrase.
      - capitalize these letters.
      - print the acronym out.

/*paste your JS generated by blockly below here */

var acronym, Outcome, item;


acronym = window.prompt('Please insert your phrase!');
acronym = acronym.toUpperCase();
acronym = acronym.split(' ');
Outcome = '';
for (var item_index in acronym) {
  item = acronym[item_index];
  Outcome += String(item.charAt(0));
}
window.alert(Outcome);